### ISSUE TITLE
Improve debugging logs

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/runbook.md#180]
- e2e tracing from change-api to biz-ops
- dashboard to tie them all together would be good

**Comment by lucas42** [comment]
Can we also downgrade any `console.error` logs which are expected in normal operation?
Examples I've spotted of this:

* repo doesn't have a `.github/runbooks.yml` file, so github API returns a 404
* commit history doesn't contain any changes to runbook.md (Though this may go away with #179)

Worth also doing a quick audit of other logs in splunk with a level of `error` to see which are genuine problems.

**Comment by doramatadora** [comment]
[X] e2e tracing - done
[ ] dashboard

@lucas42 the Change API - runbook.md flow has had a complete overhaul and logging is now vastly improved. I think your concerns will be fully addressed in the next release.

**Comment by lucas42** [comment]
Looks like using Probot has addressed the issue with the `runbooks.yml` 404. 👍 

But I'm still seeing BAILED `No runbooks found in tree` errors appearing for the second case.
I think these could be reduced to info.

**Comment by lucas42** [comment]
After the combination of Dora's & my changes, the number of `error` level logs has dropped considerably.  Hopefully it'll make it easier to spot real errors now.
